# Configurar datos de conexión hacia la DB por default de H2
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.url=jdbc:h2:file:./data/modulo40
spring.datasource.url=jdbc:mysql://localhost:3306/modulo60
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.driverClassName=com.mysql.jdbc.Driver
#spring.datasource.username=sa
#spring.datasource.password=
spring.datasource.username=root
spring.datasource.password=root
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Habilitar la consola web de H2
#spring.h2.console.enabled=true